name: unscripted
version: 0.6.2
author: Sean Eagan <seaneagan1@gmail.com>
description: Declarative command-line interface programming.
homepage: http://github.com/seaneagan/unscripted
dependencies:
  ansicolor: '>=0.0.9 <0.1.0'
  args: '>=0.11.0 <2.0.0'
  collection: '>=1.1.0 <2.0.0'
  mockable_filesystem: '>=0.0.3 <0.1.0'
  path: '>=1.3.3 <2.0.0'
  supports_color: '>=0.1.1 <0.2.0'
dev_dependencies:
  grinder: '>=0.7.1+3'
  test: ^0.12.32+1
